In [1]:
import pandas as pd
import numpy as np

print("Pandas Version: " + pd.__version__)
print("Numpy Version: " + np.__version__)

Pandas Version: 1.2.0
Numpy Version: 1.18.5

In [21]:
trips = pd.read_csv("../data/clean/trips.csv", parse_dates=["date_from", "date_until"])
trips.head(3)

,bike_id,user_id,date_from,date_until,start_station_name,start_station_id,end_station_name,end_station_id,booked_via,duration_in_min,distance_in_km
0,143517,A821059B555C7764A2FF801180874A2FCB326222,2014-01-01 00:34:54,2014-01-01 00:50:14,U-Bahn Baumwall,214170,Mönckebergstraße / Rosenstraße,131880,iPhone SRH,16,1.293661
1,119830,1EBC930DB407ACEAE2FDE23A6CA40492EA3DFBB2,2014-01-01 01:39:55,2014-01-01 01:57:27,Bahnhof Altona Ost/Max-Brauer-Allee,131646,Schulterblatt/Eifflerstraße,131648,Android SRH,18,2.032271
2,143501,7AD2C1B70137479062A6DD73815835986677BB2D,2014-01-01 01:40:20,2014-01-01 01:53:09,Weidestraße/Biedermannplatz,211922,Jarrestraße / Rambatzweg,138376,Techniker HH_119 (-2334-),13,0.954178

In [23]:
weather = pd.read_csv("../data/clean/weather.csv", parse_dates=["datetime"])
weather.head(3)

,datetime,precip_intensity,precip_probability,precip_type,temperature,humidity,wind_speed,wind_bearing,uv_index,visibility
0,2014-01-01 00:00:00,0.0,0.0,none,1.93,0.81,3.91,161.0,0.0,9.988
1,2014-01-01 01:00:00,0.0,0.0,none,1.94,0.85,4.56,140.0,0.0,6.004
2,2014-01-01 02:00:00,0.0,0.0,none,1.81,0.85,4.12,143.0,0.0,9.988

In [24]:
# Add 'datetime' as key in preparation for merging trip and weather data

trips['merge_datetime'] = pd.to_datetime(pd.DataFrame(
    {
        'year': pd.DatetimeIndex(trips['date_from']).year,
        'month': pd.DatetimeIndex(trips['date_from']).month,
        'day': pd.DatetimeIndex(trips['date_from']).day,
        'hour': pd.DatetimeIndex(trips['date_from']).hour
    }
))

In [25]:
# Add weather data to every trip

combined = pd.merge(trips, weather, left_on="merge_datetime", right_on="datetime", right_index=False)
combined.drop(columns=["merge_datetime", "datetime"], inplace=True)
combined.head(3)

,bike_id,user_id,date_from,date_until,start_station_name,start_station_id,end_station_name,end_station_id,booked_via,duration_in_min,distance_in_km,precip_intensity,precip_probability,precip_type,temperature,humidity,wind_speed,wind_bearing,uv_index,visibility
0,143517,A821059B555C7764A2FF801180874A2FCB326222,2014-01-01 00:34:54,2014-01-01 00:50:14,U-Bahn Baumwall,214170,Mönckebergstraße / Rosenstraße,131880,iPhone SRH,16,1.293661,0.0,0.0,none,1.93,0.81,3.91,161.0,0.0,9.988
1,120450,2C6FD52D5611B4DAC29E5197B67979D583685948,2014-01-01 00:27:47,2014-01-01 00:34:41,Lange Reihe / Lohmühlenpark,138385,Hauptbahnhof Ost / Hachmannplatz,131873,IVR,7,0.786254,0.0,0.0,none,1.93,0.81,3.91,161.0,0.0,9.988
2,117503,253528F56A582E05F13D8A89B20A23800DDEBEF2,2014-01-01 00:49:02,2014-01-01 00:56:32,Sternschanze / Eingang Dänenweg,139501,Bahnhof Dammtor Süd / Marseiller Straße,138382,iPhone SRH,8,1.422850,0.0,0.0,none,1.93,0.81,3.91,161.0,0.0,9.988

In [27]:
combined.to_csv("../data/clean/combined.csv")